### ISSUE TITLE
Supermarket.chef.io

### ISSUE THREAD

**Issue by MarkGibbons** [chef-customers/knife-tidy#37]
Any chance this plugin could be published on the supermarket.chef.io tools page.  It's hard to find here.

Thanks,
  Mark

**Comment by jeremymv2** [comment]
Thanks @MarkGibbons for this suggestion and sorry for the inconvenience.

We have it on Supermarket now!!

https://supermarket.chef.io/tools?utf8=%E2%9C%93&q=tidy&platforms%5B%5D=
