### ISSUE TITLE
notify subcommand ignores --orgs option

### ISSUE THREAD

**Issue by haidangwa** [chef-customers/knife-tidy#59]
`knife tidy notify --help` indicates that `--orgs` is an option for this subcommand. However, running it with the explicit intention to only notify one or more specified orgs is ignored. The process proceeds to send notifiations to all chef orgs in my chef server reports folder.

REPRO:
1. Ensure there are files generated in the reports folder
2. Run `knife tidy notify --orgs <org_name>`

The notifications are sent out for all chef orgs. It appears `--orgs` option is ignored.

knife-tidy version 0.6.1

**Comment by jonlives** [comment]
Thanks for the report @haidangwa - I'll take a look at this :)

**Comment by itmustbejj** [comment]
https://github.com/chef-customers/knife-tidy/pull/60

**Comment by itmustbejj** [comment]
merged.
